### ISSUE TITLE
Unnecessary use of `RefCell`

### ISSUE THREAD

**Issue by Lucretiel** [darthdeus/comfy#10]
Currently, `EngineContext` has a lot of "reference-to-`RefCell`" objects, presumably to allow shared mutability of the `EngineState`:

https://github.com/darthdeus/comfy/blob/5974b7c32ac614db18514071b54d176ec4282056/comfy/src/context.rs#L52-L54

However, the only way to create an `EngineContext` is with `make_context`, which takes a mutable reference to the `EngineState`. This means that all of these `&RefCell<T>` objects could instead be `&mut RefCell<T>` or even `&mut T`, though the latter would be a substantial breaking change to the API surface.

`&mut RefCell<T>` would be nice to provide for users of `EngineContext`, because it has `get_mut`, which allows for getting a mutable reference to the inner object *without* any of the normal runtime penalties associated with `borrow` or `borrow_mut`. Designs that don't need interior mutability could take advantage of `get_mut` and avoid those penalties.

**Comment by darthdeus** [comment]
Interesting, I wasn't aware of `get_mut` and just "swallowed" the runtime penalty until now, hence why it was `&` and not `&mut`. The reason these aren't `&mut T` is to allow helper methods on the context object without  running into partial borrow issues. I'll fix the references to be `&mut` soon-ish.
