### ISSUE TITLE
Benchmarks/performance regressions CI?

### ISSUE THREAD

**Issue by darthdeus** [darthdeus/comfy#16]
While comfy is not attempting to be the fastest engine out there I'd like to setup some benchmarks, and track performance improvements/regressions over time. I'm already working on porting the benchmark bevy uses https://github.com/bevyengine/bevy/issues/8100 so that we have at least some comparison, but would be nice if there was an easy way to do this in CI? Not sure if it's possible, but ... if someone wants to, I feel the whole Rust ecosystem might benefit from having a few simple benchmarks :)

In a spirit similar to #15 I'd like to have something "simple enough" that we can just have run to track how comfy performs over time. There's _many_ things in the internals that need cleanup and light rewriting, and I do expect performance improvements from some of those. I'm not sure if something like rendering benchmarks are realistic to run in CI?

If it's not possible to do in CI I'd still at least aim to have a 1 button benchmark that anyone can run that'll just run the correct things, measure a few things, and print out a table that can be copy pasted anywhere for reference.

**Comment by rparrett** [comment]
Just want to point out that `bevymark` (an approximation of bunnymark) is more commonly used / the "official in-repo sprite benchmark."

I would love this for bevy too, but I think to get any meaningful numbers out of it, you would need dedicated hardware.

**Comment by darthdeus** [comment]
Hmm I guess if CI isn't consistent enough the simple solution would be to just have a `make comfymark` that anyone can run to get current results printed somewhere nicely. I could then re-run them on my machine and add them to a page on the website whenever something notable changes.

It's not perfect, but if it's 1 button to re-run people won't have to trust me once comfy performs well and they'll be able to re-run it themselves :grimacing:

I've looked at the bevymark and looks like it should be relatively easy to port, maybe the more annoying part will be adding things like "run for 5 seconds, measure average fps, print to a file" or something, but ... we can't let that and other imperfections stand in the way of having _some_ benchmarks.

**Comment by darthdeus** [comment]
We now have https://github.com/darthdeus/comfy-benchmark which mostly solves this.
