### ISSUE TITLE
`comfy_game!` papercuts

### ISSUE THREAD

**Issue by aochagavia** [darthdeus/comfy#19]
On v0.12, I would expect the following code to compile, but it doesn't:

```rust
use comfy::{comfy_game, EngineContext};
comfy_game!("Test", MyContext, MyGameState, make_context, setup, update);

fn make_context(state: &mut MyGameState, engine: &mut EngineContext<'_>) -> MyContext { MyContext }
fn setup(_: &mut MyContext) {}
fn update(_: &mut MyContext) {}

struct MyContext;
struct MyGameState;
```

### Causes and possible solutions

The program fails to compile because:

- The `comfy_game!` macro assumes that some functions from `comfy` have been imported (if the user adds `use comfy::*` to the source file, this problem goes away). IMO it would be cleaner to use absolute paths in the macro, so the user doesn't have to care about imports.
- The `comfy_game!` macro still has a hardcoded reference to `GameState` (this seems to have been [resolved on master](https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L154))

**Comment by Lucretiel** [comment]
I believe both of these problems have been resolved with #7; can you retry with a version that includes it? I tried to catch all of the unqualified imports so let me know if I missed any.

**Comment by Lucretiel** [comment]
Whoops, identified a few more sites where this is still broken:

https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L169
https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L133
https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L140
https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L149
https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L164
https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L145
https://github.com/darthdeus/comfy/blob/5a3c8934ae4d4026710ddc0ba44fea3772e46a4c/comfy/src/macros.rs#L130

I'm about to get on a plane so I don't have time to fix these now, but all of these should be fixable by prefixing the import with `$crate::`.

**Comment by darthdeus** [comment]
This should be now fixed on master, including a bunch more of these missing.

Note that the example needs a `MyGameState::new(...)`, so a small change to make it compile

```rust
use comfy::{comfy_game, EngineContext};
comfy_game!("Test", MyContext, MyGameState, make_context, setup, update);

fn make_context(state: &mut MyGameState, engine: &mut EngineContext<'_>) -> MyContext { MyContext }
fn setup(_: &mut MyContext) {}
fn update(_: &mut MyContext) {}

struct MyContext;
struct MyGameState;

impl MyGameState {
    fn new(_c: &EngineContext) -> Self { Self }
}
```
