### ISSUE TITLE
Color test example

### ISSUE THREAD

**Issue by darthdeus** [darthdeus/comfy#37]
Comfy currently struggles with colors. What many probably attribute to the "comfy look" is in part actually a bug :)

Once the bug is fixed I'd still like to preserve "the comfy look" with a post processing shader, but it should also be possible to render accurate colors.

This includes things like `draw_circle(..., RED)` actually being true RGBA RED, and not a comfy pink-ish red.

In order to test this, we need an example that draws a bunch of standardized gradients (like egui color test for example here https://github.com/setzer22/godot-egui/issues/14) so that we have a baseline comparison and figure out what's wrong. I suspect something with sRGB, but it'd be great to have this to avoid regressions in the future, and also maybe to test interesting color mapping effects afterwards :)

Note that this issue is not about fixing the actual rendering issue, it's only about creating a color test so we can better diagnose problems with colors, and ultimately lighting as well.

**Comment by nuts-rice** [comment]
Hi there, I have a few color maps for different pallets that I got to work with the existing colors test, could contribute

**Comment by darthdeus** [comment]
This is now implemented in the [`colors` example](https://github.com/darthdeus/comfy/blob/master/comfy/examples/colors.rs)
