### ISSUE TITLE
timed_draw example not clearing background

### ISSUE THREAD

**Issue by Toby222** [darthdeus/comfy#57]
The `timed_draw` example doesn't work as it seems to be intended, the drawn texture remains after the 3 second counter (though it doesn't get redrawn, and gets squished if I resize the window)

Running on Wayland/Sway

![example of graphics with drawn texture remaining after supposed clear](https://github.com/darthdeus/comfy/assets/14962962/c2f69c89-9314-454a-a6d3-4a8bc39f3cdd)

**Comment by darthdeus** [comment]
Duplicate of #34, fix coming soon.
