### ISSUE TITLE
How to set the game window size in Comfy Engine?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [darthdeus/comfy#75]
I did not find relevant instructions in the documentation. If possible, could you provide more documentation content? This would be very helpful for beginners like me.

**Comment by tomoliveirabastos** [comment]
i solved it with this way

fn setup(c: &mut EngineContext) {
    c.renderer.window().set_inner_size(LogicalSize::new(400.0, 200.0));
}

**Comment by darthdeus** [comment]
If you only need to set this on startup you can use the game config as shown in this example https://github.com/darthdeus/comfy/blob/master/comfy/examples/custom_config.rs

**Comment by darthdeus** [comment]
The linked example is for `master`, which has the main loop setup slightly different than comfy `v0.2`. There's a few differences around the game loop on `master`, you can see https://github.com/darthdeus/comfy/blob/master/CHANGELOG.md for the list of upcoming changes.

That being said, here's the version of that example for `v0.2` https://github.com/darthdeus/comfy/blob/v0.2.0/comfy/examples/custom_config.rs
